# Generated by Django 3.1.3 on 2021-04-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('candidate_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('candidate_logo', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
