# Generated by Django 3.1.3 on 2021-04-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='vote_count',
            field=models.IntegerField(null=True),
        ),
    ]
